apiVersion: v1
kind: Service
metadata:
  name: customer-success-api-service
  namespace: customer-success-fte
  labels:
    app: customer-success-api
spec:
  selector:
    app: customer-success-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: customer-success-internal-service
  namespace: customer-success-fte
  labels:
    app: customer-success-worker
spec:
  selector:
    app: customer-success-worker
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
